import "./globals.css";
import { Inter } from "next/font/google";

// Body по умолчанию Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mydark" className={`scroll-smooth`}>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
